### ISSUE TITLE
Open issues not working

### ISSUE THREAD

**Issue by JoshClose** [dessant/issue-states#1]
When moving items out of `Done` and into the other columns, it's not opening the issues again.

This is my config located in the root of my repository `.github/issue-states.yml`

```yml
# Configuration for issue-states - https://github.com/dessant/issue-states

# Open issues that are moved to these project columns. Set to `[]` to disable
openIssueColumns:
  - Backlog
  - In Progress
  - Blocked

# Close issues that are moved to these project columns. Set to `[]` to disable
closedIssueColumns:
  - Closed
  - Done

# Repository to extend settings from
# _extends: repo
```
