### ISSUE TITLE
Doesn't work as scheduled task

### ISSUE THREAD

**Issue by yaeszlo** [dessant/issue-states#4]
Hello, I was trying to use your action as scheduled task, because wasting GH minutes each time I move 1 card doesn't seem to attractive. My workflow: 

```

name: 'Sync issue status'

on:
  schedule:
    - cron: '30 18 * * 1-5'
  workflow_dispatch:

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v2
```

This is failing. Any way to make it work?
